all:
	rm -f kalman_filter_1d_demo
	clear
	@echo "Let us build the project kalman_filter_1d_demo"
	g++ -Wall *.cpp \
	    -o kalman_filter_1d_demo \
		`pkg-config --cflags --libs opencv4`
	@echo CODE COMPILED SUCCESSFULLY!