all:
	rm -f particle_filter_demo
	clear
	@echo "Let us build the project: particle_filter_demo"
	g++ -Wall *.cpp \
	    -o particle_filter_demo \
		`pkg-config --cflags --libs opencv4`
	@echo CODE COMPILED SUCCESSFULLY!
