all:
	rm -f robot_localization_with_a_map
	clear
	@echo "Let us build the project robot_localization_with_a_map"
	g++ -Wall *.cpp \
	    -o robot_localization_with_a_map \
		`pkg-config --cflags --libs opencv4`
	@echo CODE COMPILED SUCCESSFULLY!